name: 'Delete Comment'
description: 'delete comments from issue/pr by username'
author: 'izhangzhihao'
inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  delete_user_name:
    description: 'Github username to delete comments'
    default: 'open-collective-bot[bot]'
    required: false
  issue_number:
    description: 'Issue/PR on which to delete comments. If not provided, comments will be deleted across the repo.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
